/***** slave.js **************************************************************
 *                                                                           *
 *  Creator: Bruce Herring                                                   *
 *  Created: 2/3/00                                                          *
 *                                                                           *
 *  Intended Use:  This file is inteneded to be used in conjuction with      *
 *                 the html files that are generated by Dave Whalley tool    *
 *                 that I modified.                                          *
 *                                                                           *
 *****************************************************************************/

/****** change_script ********************************************************
 *                                                                           *
 *  Changes the lower windows contents location to the location indicated    *
 *  by script                                                                *
 *                                                                           *
 *****************************************************************************/

function change_script (script) {
    if (top.location != self.location)
        parent.lower.document.location.href = script
}


/****** change_frames ********************************************************
 *                                                                           *
 *  Switches between framed and non framed environment.                      *
 *  If you start with the non-frame version and then go to frames            *
 *  their will always be a ? in the URL.  This is the way I intended         *
 *  the files to be used.  If you start with the framed version the first    *
 *  time you try to go to non-framed it will appear to do nothing.  The      *
 *  second time it will work.                                                *
 *                                                                           *
 *  Actualy this function simply returns the address of the appropriate      *
 *  page.  The .html file that recieves it will use it appropriately.        *
 *                                                                           *
 *****************************************************************************/

function change_frames () {
    if (top.document.URL.indexOf ("$$$") != -1)
        return self.document.URL
    else {
	path = document.URL.split ("/")
	return ("index.html?$$$" + path[path.length - 1] + "$$$")
    }
}


/****** script_viewable ******************************************************
 *                                                                           *
 *  Returns 'frame' if the second frame is viewable, otherwise it returns    *
 *  'script'. See change_frames for further information.                     *
 *                                                                           *
 * *****************************************************************************/

function script_viewable () {
    if (top.document.URL.indexOf ("$$$") != -1)
        return "Frame"
    else {
        return "Script"
	}
}


/****** get_upper_frame ******************************************************
 *                                                                           *
 *  Returns all the information between the $$$'s in the sites url. If there *
 *  is more than two $$$'s in the URL only the information between the first *
 *  and second $$$ will be returned.  If there are no $$$'s in the URL       *
 *  toc.html will be returned.                                               *
 *                                                                           *
 *****************************************************************************/

function get_upper_frame () {
    path = top.document.URL.split ("$$$")
    if (path[0].length != top.document.URL.length)
       return path[1]
    else
       return "toc.html"
}
